Fixed broken makefiles (again).
Made CC1120 driver slightly more generic than just msp430.

fixed bugs in spi.c and cc1120-mkl25z-rf-arch.c.

This compiles @hello-world@, but cannot compile IPv6 examples due to undefined reference to uip_log